variables:
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]

trigger:
- main
- dev

stages:
  - stage: ScanAndCommit
    variables:
    - group: omg-azure-developer
    pool:
      vmImage: ubuntu-latest
    displayName: Prepare
    jobs:
      - job: ScanAndBuild
        workspace:
          clean: all
        displayName: Security Scan
        steps:
          - checkout: self
            fetchDepth: 4
          - template: azure-templates/scanandbuild.yml
            parameters:
              dataResidency: DEV
  
  - stage: DeployDev
    variables:
    - group: omg-azure-developer
    displayName: Deploy to DEV
    dependsOn: ScanAndCommit
    condition: |
      and(
        succeeded('ScanAndCommit'),
        eq(variables.isDev, 'true')
      )
    jobs:
    - template: azure-templates/deploy-dev.yml
      parameters:
        dataResidency: DEV
        agentPool: omg-gridos-amd

  - stage: DeployProd
    variables:
    - group: omg-azure-production
    displayName: Deploy to PROD
    dependsOn: ScanAndCommit
    condition: |
      and(
        succeeded('ScanAndCommit'),
        eq(variables.isMain, 'true')
      )
    jobs:
    - template: azure-templates/deploy-prod.yml
      parameters:
        dataResidency: EU
        agentPool: omg-gridos-amd