jobs:
  - job: "BuildDev"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    pool: ${{ parameters.agentPool }}
    steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(build.sourcesDirectory)'
          includeRootFolder: false
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dev.zip"
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dev.zip"
          artifactName: "build-dev"
          publishLocation: "Container"
  - job: approve
    displayName: Approve
    dependsOn: BuildDev
    condition: succeeded()
    pool: server
    steps:
    - template: approve.yml
  - job: DeployToDev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    pool: ${{ parameters.agentPool }}
    displayName: Deploy
    dependsOn: approve
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Downloading Artifact
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'build-dev'
          downloadPath: '$(System.DefaultWorkingDirectory)'
      - task: ExtractFiles@1
        displayName: Extract files
        inputs:
          archiveFilePatterns: '$(System.DefaultWorkingDirectory)/build-dev/$(Build.BuildId)-dev.zip'
          destinationFolder: '$(System.DefaultWorkingDirectory)/_ombori.grid-docs/web'
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'omg-dev'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob upload-batch \
              --source "$(System.DefaultWorkingDirectory)/_ombori.grid-docs/web/" \
              --destination '$web' \
              --account-name 'omggriddocsdev'