jobs:
  - job: "BuildDev"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    pool: ${{ parameters.agentPool }}
    steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(build.sourcesDirectory)'
          includeRootFolder: false
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dev.zip"
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-dev.zip"
          artifactName: "build-dev"
          publishLocation: "Container"
  - job: approve
    displayName: Approve
    dependsOn: BuildDev
    condition: succeeded()
    pool: server
    steps:
    - template: tf-approve.yml
  - job: DeployToDev
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    pool: ${{ parameters.agentPool }}
    displayName: Approve
    dependsOn: approve
    steps:
    - task: ExtractFiles
      displayName: 'Extract files'
      inputs:
        archiveFilePatterns: '$(System.DefaultWorkingDirectory)/_ombori.grid-docs/build-dev/*.zip'
        destinationFolder: '$(System.DefaultWorkingDirectory)/_ombori.grid-docs/web'
    - task: AzureFileCopy
      displayName: 'AzureBlob File Copy'
      inputs:
        SourcePath: '$(System.DefaultWorkingDirectory)/_ombori.grid-docs/web/*'
        azureSubscription: 'Azure Production (EA) Service Connection'
        Destination: AzureBlob
        storage: griddocsdev
        ContainerName: '$web'